controller:
  serviceType: ClusterIP
  admin:
    username: "admin"
    password: "password"
  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - cloudbees-folder:latest
    - matrix-auth:latest
    - role-strategy:latest
    - workflow-aggregator:latest

  JCasC:
    enabled: true
    configScripts:
      jenkins: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "password"
          authorizationStrategy:
            projectMatrix:
              permissions:
                - "Overall/Administer:admin"

  javaOpts: >-
    -Xmx2g
    -Xms2g
    -Dhudson.model.DirectoryBrowserSupport.CSP=
    -Djenkins.install.runSetupWizard=false

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  probes:
    startupProbe:
      failureThreshold: 12
      periodSeconds: 10
      initialDelaySeconds: 60
    livenessProbe:
      failureThreshold: 5
      periodSeconds: 10
      initialDelaySeconds: 60
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 60

persistence:
  enabled: true
  storageClass: local-storage
  size: 10Gi
  accessMode: ReadWriteOnce

serviceAccount:
  create: true

rbac:
  create: true